<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
<img onClick="checkout()" src="https://static.masterpass.com/dyn/img/btn/global/mp_chk_btn_147x034px.svg"/>
</body>
</html>

<!-- Sandbox -->
<script type="text/javascript" src="https://sandbox.masterpass.com/integration/merchant.js"></script>

<!-- Production -->
<script type="text/javascript" src="https://masterpass.com/integration/merchant.js"></script>

<script type="text/javascript" >
 function checkout(){
	 masterpass.checkout({
	        "checkoutId": "c26966b0eae94a3fbe47f994b94394b2",                                   // Merchant checkout identifier received when merchant onboarded for masterpass
	        "allowedCardTypes": ["master,amex,diners,discover,jcb,maestro,visa"],               // Card types accepted by merchant
	        "amount": "1.00",                                                                 // Shopping cart subtotal
	        "currency": "USD",                                                                  // Currency code for cart
	        "shippingLocationProfile": "US,AU,BE",                                              // Shipping locations supported by merchant - configured in merchant portal
	        "suppress3Ds": false,                                                               // Set true when 3DS not mandatory for the spcecific country
	        "suppressShippingAddress": false,                                                   // Set true when cart items has digital goods only
	        "cartId": "1efed583-1824-436a-869f-286ebdb22ae2",                                   // Unique identifier for cart generated by merchant
	        "callbackUrl": "https://masterpass-checkout.herokuapp.com/callback"                                  // The URL to which the browser must redirect when checkout is complete
	});

 } 
</script>

